version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: botuser
      MONGO_INITDB_ROOT_PASSWORD: botpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: bot_backend
    environment:
      MONGO_URI: mongodb://botuser:botpass@mongodb:27017
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongo_data:

